name: horoscope_guide
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.3.8
  cloud_firestore: ^3.1.0
  firebase_core: ^1.8.0
  firebase_auth: ^3.2.0
  lottie: ^1.2.1
  provider: ^6.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/horoscopes/

